name: declarative_animated_list
description: An implementation of animated list widget that will be automatically updated based on different lists snippets.
version: 0.0.2
authors:
  - Andrii Iliunin <orkay255@gmail.com>
  - New Line Technologies <a.iliunin@newlinetechnologies.net>
homepage: https://github.com/nyarian/declarative_animated_list
repository: https://bitbucket.org/ilyunin111/declarative_animated_list
issue_tracker: https://github.com/nyarian/declarative_animated_list/issues

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 4.1.0
